package com.qf.entity;

import java.util.Date;

public class All {
    private Integer collectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer usId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.book_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.collect_id
     *
     * @return the value of collect.collect_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getCollectId() {
        return collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.collect_id
     *
     * @param collectId the value for collect.collect_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setCollectId(Integer collectId) {
        this.collectId = collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.us_id
     *
     * @return the value of collect.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.us_id
     *
     * @param usId the value for collect.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.book_id
     *
     * @return the value of collect.book_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.book_id
     *
     * @param bookId the value for collect.book_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
//    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.book_name
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.type_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
//    private Integer usId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.book_details
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String bookDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.book_comment
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String bookComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.book_pageView
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer bookPageview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.book_grade
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Double bookGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.book_collect
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer bookCollect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.book_image
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String bookImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookbook.book_time
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Date bookTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.book_Id
     *
     * @return the value of cookbook.book_Id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
//    public Integer getBookId() {
//        return bookId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.book_Id
     *
     * @param bookId the value for cookbook.book_Id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
//    public void setBookId(Integer bookId) {
//        this.bookId = bookId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.book_name
     *
     * @return the value of cookbook.book_name
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.book_name
     *
     * @param bookName the value for cookbook.book_name
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.type_id
     *
     * @return the value of cookbook.type_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.type_id
     *
     * @param typeId the value for cookbook.type_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.us_id
     *
     * @return the value of cookbook.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
//    public Integer getUsId() {
//        return usId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.us_id
     *
     * @param usId the value for cookbook.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
//    public void setUsId(Integer usId) {
//        this.usId = usId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.book_details
     *
     * @return the value of cookbook.book_details
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getBookDetails() {
        return bookDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.book_details
     *
     * @param bookDetails the value for cookbook.book_details
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookDetails(String bookDetails) {
        this.bookDetails = bookDetails == null ? null : bookDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.book_comment
     *
     * @return the value of cookbook.book_comment
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getBookComment() {
        return bookComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.book_comment
     *
     * @param bookComment the value for cookbook.book_comment
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookComment(String bookComment) {
        this.bookComment = bookComment == null ? null : bookComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.book_pageView
     *
     * @return the value of cookbook.book_pageView
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getBookPageview() {
        return bookPageview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.book_pageView
     *
     * @param bookPageview the value for cookbook.book_pageView
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookPageview(Integer bookPageview) {
        this.bookPageview = bookPageview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.book_grade
     *
     * @return the value of cookbook.book_grade
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Double getBookGrade() {
        return bookGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.book_grade
     *
     * @param bookGrade the value for cookbook.book_grade
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookGrade(Double bookGrade) {
        this.bookGrade = bookGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.book_collect
     *
     * @return the value of cookbook.book_collect
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getBookCollect() {
        return bookCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.book_collect
     *
     * @param bookCollect the value for cookbook.book_collect
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookCollect(Integer bookCollect) {
        this.bookCollect = bookCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.book_image
     *
     * @return the value of cookbook.book_image
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getBookImage() {
        return bookImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.book_image
     *
     * @param bookImage the value for cookbook.book_image
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookImage(String bookImage) {
        this.bookImage = bookImage == null ? null : bookImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookbook.book_time
     *
     * @return the value of cookbook.book_time
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Date getBookTime() {
        return bookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookbook.book_time
     *
     * @param bookTime the value for cookbook.book_time
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setBookTime(Date bookTime) {
        this.bookTime = bookTime;
    }
//    private Integer usId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_name
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String usName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_password
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String usPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_mobile
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Long usMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_email
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String usEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_message
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String usMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_sex
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer usSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_birthday
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Date usBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_nowhome
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String usNowhome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_job
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String usJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_head
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private String usHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_fansCount
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer usFanscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_bookCount
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Integer usBookcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.us_createdate
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    private Date usCreatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_id
     *
     * @return the value of user.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
//    public Integer getUsId() {
//        return usId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_id
     *
     * @param usId the value for user.us_id
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
//    public void setUsId(Integer usId) {
//        this.usId = usId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_name
     *
     * @return the value of user.us_name
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getUsName() {
        return usName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_name
     *
     * @param usName the value for user.us_name
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsName(String usName) {
        this.usName = usName == null ? null : usName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_password
     *
     * @return the value of user.us_password
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getUsPassword() {
        return usPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_password
     *
     * @param usPassword the value for user.us_password
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsPassword(String usPassword) {
        this.usPassword = usPassword == null ? null : usPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_mobile
     *
     * @return the value of user.us_mobile
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Long getUsMobile() {
        return usMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_mobile
     *
     * @param usMobile the value for user.us_mobile
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsMobile(Long usMobile) {
        this.usMobile = usMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_email
     *
     * @return the value of user.us_email
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getUsEmail() {
        return usEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_email
     *
     * @param usEmail the value for user.us_email
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsEmail(String usEmail) {
        this.usEmail = usEmail == null ? null : usEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_message
     *
     * @return the value of user.us_message
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getUsMessage() {
        return usMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_message
     *
     * @param usMessage the value for user.us_message
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsMessage(String usMessage) {
        this.usMessage = usMessage == null ? null : usMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_sex
     *
     * @return the value of user.us_sex
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getUsSex() {
        return usSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_sex
     *
     * @param usSex the value for user.us_sex
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsSex(Integer usSex) {
        this.usSex = usSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_birthday
     *
     * @return the value of user.us_birthday
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Date getUsBirthday() {
        return usBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_birthday
     *
     * @param usBirthday the value for user.us_birthday
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsBirthday(Date usBirthday) {
        this.usBirthday = usBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_nowhome
     *
     * @return the value of user.us_nowhome
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getUsNowhome() {
        return usNowhome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_nowhome
     *
     * @param usNowhome the value for user.us_nowhome
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsNowhome(String usNowhome) {
        this.usNowhome = usNowhome == null ? null : usNowhome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_job
     *
     * @return the value of user.us_job
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getUsJob() {
        return usJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_job
     *
     * @param usJob the value for user.us_job
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsJob(String usJob) {
        this.usJob = usJob == null ? null : usJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_head
     *
     * @return the value of user.us_head
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public String getUsHead() {
        return usHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_head
     *
     * @param usHead the value for user.us_head
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsHead(String usHead) {
        this.usHead = usHead == null ? null : usHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_fansCount
     *
     * @return the value of user.us_fansCount
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getUsFanscount() {
        return usFanscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_fansCount
     *
     * @param usFanscount the value for user.us_fansCount
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsFanscount(Integer usFanscount) {
        this.usFanscount = usFanscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_bookCount
     *
     * @return the value of user.us_bookCount
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Integer getUsBookcount() {
        return usBookcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_bookCount
     *
     * @param usBookcount the value for user.us_bookCount
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsBookcount(Integer usBookcount) {
        this.usBookcount = usBookcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.us_createdate
     *
     * @return the value of user.us_createdate
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public Date getUsCreatedate() {
        return usCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.us_createdate
     *
     * @param usCreatedate the value for user.us_createdate
     *
     * @mbggenerated Tue Apr 09 21:23:38 CST 2019
     */
    public void setUsCreatedate(Date usCreatedate) {
        this.usCreatedate = usCreatedate;
    }
}
