package com.qf.entity;

import java.util.Date;

public class BookComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.comment_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.book_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.us_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer usId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.comment_value
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private String commentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.comment_time
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Date commentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.comment_id
     *
     * @return the value of book_comment.comment_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.comment_id
     *
     * @param commentId the value for book_comment.comment_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.book_id
     *
     * @return the value of book_comment.book_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.book_id
     *
     * @param bookId the value for book_comment.book_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.us_id
     *
     * @return the value of book_comment.us_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.us_id
     *
     * @param usId the value for book_comment.us_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.comment_value
     *
     * @return the value of book_comment.comment_value
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public String getCommentValue() {
        return commentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.comment_value
     *
     * @param commentValue the value for book_comment.comment_value
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setCommentValue(String commentValue) {
        this.commentValue = commentValue == null ? null : commentValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.comment_time
     *
     * @return the value of book_comment.comment_time
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.comment_time
     *
     * @param commentTime the value for book_comment.comment_time
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }
}