package com.qf.entity;

import java.util.ArrayList;
import java.util.List;

public class ConsigneeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public ConsigneeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConIdIsNull() {
            addCriterion("con_id is null");
            return (Criteria) this;
        }

        public Criteria andConIdIsNotNull() {
            addCriterion("con_id is not null");
            return (Criteria) this;
        }

        public Criteria andConIdEqualTo(Integer value) {
            addCriterion("con_id =", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotEqualTo(Integer value) {
            addCriterion("con_id <>", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdGreaterThan(Integer value) {
            addCriterion("con_id >", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("con_id >=", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdLessThan(Integer value) {
            addCriterion("con_id <", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdLessThanOrEqualTo(Integer value) {
            addCriterion("con_id <=", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdIn(List<Integer> values) {
            addCriterion("con_id in", values, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotIn(List<Integer> values) {
            addCriterion("con_id not in", values, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdBetween(Integer value1, Integer value2) {
            addCriterion("con_id between", value1, value2, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotBetween(Integer value1, Integer value2) {
            addCriterion("con_id not between", value1, value2, "conId");
            return (Criteria) this;
        }

        public Criteria andUsIdIsNull() {
            addCriterion("us_id is null");
            return (Criteria) this;
        }

        public Criteria andUsIdIsNotNull() {
            addCriterion("us_id is not null");
            return (Criteria) this;
        }

        public Criteria andUsIdEqualTo(Integer value) {
            addCriterion("us_id =", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdNotEqualTo(Integer value) {
            addCriterion("us_id <>", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdGreaterThan(Integer value) {
            addCriterion("us_id >", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("us_id >=", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdLessThan(Integer value) {
            addCriterion("us_id <", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdLessThanOrEqualTo(Integer value) {
            addCriterion("us_id <=", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdIn(List<Integer> values) {
            addCriterion("us_id in", values, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdNotIn(List<Integer> values) {
            addCriterion("us_id not in", values, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdBetween(Integer value1, Integer value2) {
            addCriterion("us_id between", value1, value2, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("us_id not between", value1, value2, "usId");
            return (Criteria) this;
        }

        public Criteria andConNameIsNull() {
            addCriterion("con_name is null");
            return (Criteria) this;
        }

        public Criteria andConNameIsNotNull() {
            addCriterion("con_name is not null");
            return (Criteria) this;
        }

        public Criteria andConNameEqualTo(String value) {
            addCriterion("con_name =", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameNotEqualTo(String value) {
            addCriterion("con_name <>", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameGreaterThan(String value) {
            addCriterion("con_name >", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameGreaterThanOrEqualTo(String value) {
            addCriterion("con_name >=", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameLessThan(String value) {
            addCriterion("con_name <", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameLessThanOrEqualTo(String value) {
            addCriterion("con_name <=", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameLike(String value) {
            addCriterion("con_name like", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameNotLike(String value) {
            addCriterion("con_name not like", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameIn(List<String> values) {
            addCriterion("con_name in", values, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameNotIn(List<String> values) {
            addCriterion("con_name not in", values, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameBetween(String value1, String value2) {
            addCriterion("con_name between", value1, value2, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameNotBetween(String value1, String value2) {
            addCriterion("con_name not between", value1, value2, "conName");
            return (Criteria) this;
        }

        public Criteria andConMobileIsNull() {
            addCriterion("con_mobile is null");
            return (Criteria) this;
        }

        public Criteria andConMobileIsNotNull() {
            addCriterion("con_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andConMobileEqualTo(Long value) {
            addCriterion("con_mobile =", value, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConMobileNotEqualTo(Long value) {
            addCriterion("con_mobile <>", value, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConMobileGreaterThan(Long value) {
            addCriterion("con_mobile >", value, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConMobileGreaterThanOrEqualTo(Long value) {
            addCriterion("con_mobile >=", value, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConMobileLessThan(Long value) {
            addCriterion("con_mobile <", value, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConMobileLessThanOrEqualTo(Long value) {
            addCriterion("con_mobile <=", value, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConMobileIn(List<Long> values) {
            addCriterion("con_mobile in", values, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConMobileNotIn(List<Long> values) {
            addCriterion("con_mobile not in", values, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConMobileBetween(Long value1, Long value2) {
            addCriterion("con_mobile between", value1, value2, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConMobileNotBetween(Long value1, Long value2) {
            addCriterion("con_mobile not between", value1, value2, "conMobile");
            return (Criteria) this;
        }

        public Criteria andConAddressIsNull() {
            addCriterion("con_address is null");
            return (Criteria) this;
        }

        public Criteria andConAddressIsNotNull() {
            addCriterion("con_address is not null");
            return (Criteria) this;
        }

        public Criteria andConAddressEqualTo(String value) {
            addCriterion("con_address =", value, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressNotEqualTo(String value) {
            addCriterion("con_address <>", value, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressGreaterThan(String value) {
            addCriterion("con_address >", value, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressGreaterThanOrEqualTo(String value) {
            addCriterion("con_address >=", value, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressLessThan(String value) {
            addCriterion("con_address <", value, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressLessThanOrEqualTo(String value) {
            addCriterion("con_address <=", value, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressLike(String value) {
            addCriterion("con_address like", value, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressNotLike(String value) {
            addCriterion("con_address not like", value, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressIn(List<String> values) {
            addCriterion("con_address in", values, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressNotIn(List<String> values) {
            addCriterion("con_address not in", values, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressBetween(String value1, String value2) {
            addCriterion("con_address between", value1, value2, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConAddressNotBetween(String value1, String value2) {
            addCriterion("con_address not between", value1, value2, "conAddress");
            return (Criteria) this;
        }

        public Criteria andConPostalIsNull() {
            addCriterion("con_postal is null");
            return (Criteria) this;
        }

        public Criteria andConPostalIsNotNull() {
            addCriterion("con_postal is not null");
            return (Criteria) this;
        }

        public Criteria andConPostalEqualTo(String value) {
            addCriterion("con_postal =", value, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalNotEqualTo(String value) {
            addCriterion("con_postal <>", value, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalGreaterThan(String value) {
            addCriterion("con_postal >", value, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalGreaterThanOrEqualTo(String value) {
            addCriterion("con_postal >=", value, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalLessThan(String value) {
            addCriterion("con_postal <", value, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalLessThanOrEqualTo(String value) {
            addCriterion("con_postal <=", value, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalLike(String value) {
            addCriterion("con_postal like", value, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalNotLike(String value) {
            addCriterion("con_postal not like", value, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalIn(List<String> values) {
            addCriterion("con_postal in", values, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalNotIn(List<String> values) {
            addCriterion("con_postal not in", values, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalBetween(String value1, String value2) {
            addCriterion("con_postal between", value1, value2, "conPostal");
            return (Criteria) this;
        }

        public Criteria andConPostalNotBetween(String value1, String value2) {
            addCriterion("con_postal not between", value1, value2, "conPostal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consignee
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 20 17:21:29 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}