package com.qf.entity;

public class Consignee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.con_id
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    private Integer conId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.us_id
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    private Integer usId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.con_name
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    private String conName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.con_mobile
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    private Long conMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.con_address
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    private String conAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.con_postal
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    private String conPostal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.con_id
     *
     * @return the value of consignee.con_id
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public Integer getConId() {
        return conId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.con_id
     *
     * @param conId the value for consignee.con_id
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void setConId(Integer conId) {
        this.conId = conId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.us_id
     *
     * @return the value of consignee.us_id
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public Integer getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.us_id
     *
     * @param usId the value for consignee.us_id
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.con_name
     *
     * @return the value of consignee.con_name
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public String getConName() {
        return conName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.con_name
     *
     * @param conName the value for consignee.con_name
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void setConName(String conName) {
        this.conName = conName == null ? null : conName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.con_mobile
     *
     * @return the value of consignee.con_mobile
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public Long getConMobile() {
        return conMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.con_mobile
     *
     * @param conMobile the value for consignee.con_mobile
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void setConMobile(Long conMobile) {
        this.conMobile = conMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.con_address
     *
     * @return the value of consignee.con_address
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public String getConAddress() {
        return conAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.con_address
     *
     * @param conAddress the value for consignee.con_address
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void setConAddress(String conAddress) {
        this.conAddress = conAddress == null ? null : conAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.con_postal
     *
     * @return the value of consignee.con_postal
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public String getConPostal() {
        return conPostal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.con_postal
     *
     * @param conPostal the value for consignee.con_postal
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    public void setConPostal(String conPostal) {
        this.conPostal = conPostal == null ? null : conPostal.trim();
    }
}