package com.qf.entity;

public class Material {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.mat_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer matId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.book_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.mat_name
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private String matName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.mat_dosage
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    private String matDosage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.mat_id
     *
     * @return the value of material.mat_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getMatId() {
        return matId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.mat_id
     *
     * @param matId the value for material.mat_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setMatId(Integer matId) {
        this.matId = matId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.book_id
     *
     * @return the value of material.book_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.book_id
     *
     * @param bookId the value for material.book_id
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.mat_name
     *
     * @return the value of material.mat_name
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public String getMatName() {
        return matName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.mat_name
     *
     * @param matName the value for material.mat_name
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setMatName(String matName) {
        this.matName = matName == null ? null : matName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.mat_dosage
     *
     * @return the value of material.mat_dosage
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public String getMatDosage() {
        return matDosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.mat_dosage
     *
     * @param matDosage the value for material.mat_dosage
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    public void setMatDosage(String matDosage) {
        this.matDosage = matDosage == null ? null : matDosage.trim();
    }
}