package com.qf.entity;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.alias
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_images
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String productImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.unit
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sort
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_massage
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String productMassage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.merit
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String merit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.recommend
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.taboo
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String taboo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sales
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Long sales;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.alias
     *
     * @return the value of product.alias
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.alias
     *
     * @param alias the value for product.alias
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_images
     *
     * @return the value of product.product_images
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getProductImages() {
        return productImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_images
     *
     * @param productImages the value for product.product_images
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setProductImages(String productImages) {
        this.productImages = productImages == null ? null : productImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.unit
     *
     * @return the value of product.unit
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.unit
     *
     * @param unit the value for product.unit
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sort
     *
     * @return the value of product.sort
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sort
     *
     * @param sort the value for product.sort
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_massage
     *
     * @return the value of product.product_massage
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getProductMassage() {
        return productMassage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_massage
     *
     * @param productMassage the value for product.product_massage
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setProductMassage(String productMassage) {
        this.productMassage = productMassage == null ? null : productMassage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.merit
     *
     * @return the value of product.merit
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getMerit() {
        return merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.merit
     *
     * @param merit the value for product.merit
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setMerit(String merit) {
        this.merit = merit == null ? null : merit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.recommend
     *
     * @return the value of product.recommend
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.recommend
     *
     * @param recommend the value for product.recommend
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend == null ? null : recommend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.taboo
     *
     * @return the value of product.taboo
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getTaboo() {
        return taboo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.taboo
     *
     * @param taboo the value for product.taboo
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setTaboo(String taboo) {
        this.taboo = taboo == null ? null : taboo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sales
     *
     * @return the value of product.sales
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Long getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sales
     *
     * @param sales the value for product.sales
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setSales(Long sales) {
        this.sales = sales;
    }

    @Override
    public String toString() {
        return "Product{" +
                "productId=" + productId +
                ", productName='" + productName + '\'' +
                ", alias='" + alias + '\'' +
                ", productImages='" + productImages + '\'' +
                ", price=" + price +
                ", unit='" + unit + '\'' +
                ", sort='" + sort + '\'' +
                ", productMassage='" + productMassage + '\'' +
                ", merit='" + merit + '\'' +
                ", recommend='" + recommend + '\'' +
                ", taboo='" + taboo + '\'' +
                ", sales=" + sales +
                '}';
    }
}