package com.qf.entity;

public class TpRegion2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_region2.id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_region2.name
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_region2.parent_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_region2.level
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    private Boolean level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_region2.id
     *
     * @return the value of tp_region2.id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_region2.id
     *
     * @param id the value for tp_region2.id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_region2.name
     *
     * @return the value of tp_region2.name
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_region2.name
     *
     * @param name the value for tp_region2.name
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_region2.parent_id
     *
     * @return the value of tp_region2.parent_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_region2.parent_id
     *
     * @param parentId the value for tp_region2.parent_id
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_region2.level
     *
     * @return the value of tp_region2.level
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_region2.level
     *
     * @param level the value for tp_region2.level
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }
}