package com.qf.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUsIdIsNull() {
            addCriterion("us_id is null");
            return (Criteria) this;
        }

        public Criteria andUsIdIsNotNull() {
            addCriterion("us_id is not null");
            return (Criteria) this;
        }

        public Criteria andUsIdEqualTo(Integer value) {
            addCriterion("us_id =", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdNotEqualTo(Integer value) {
            addCriterion("us_id <>", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdGreaterThan(Integer value) {
            addCriterion("us_id >", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("us_id >=", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdLessThan(Integer value) {
            addCriterion("us_id <", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdLessThanOrEqualTo(Integer value) {
            addCriterion("us_id <=", value, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdIn(List<Integer> values) {
            addCriterion("us_id in", values, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdNotIn(List<Integer> values) {
            addCriterion("us_id not in", values, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdBetween(Integer value1, Integer value2) {
            addCriterion("us_id between", value1, value2, "usId");
            return (Criteria) this;
        }

        public Criteria andUsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("us_id not between", value1, value2, "usId");
            return (Criteria) this;
        }

        public Criteria andUsNameIsNull() {
            addCriterion("us_name is null");
            return (Criteria) this;
        }

        public Criteria andUsNameIsNotNull() {
            addCriterion("us_name is not null");
            return (Criteria) this;
        }

        public Criteria andUsNameEqualTo(String value) {
            addCriterion("us_name =", value, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameNotEqualTo(String value) {
            addCriterion("us_name <>", value, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameGreaterThan(String value) {
            addCriterion("us_name >", value, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameGreaterThanOrEqualTo(String value) {
            addCriterion("us_name >=", value, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameLessThan(String value) {
            addCriterion("us_name <", value, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameLessThanOrEqualTo(String value) {
            addCriterion("us_name <=", value, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameLike(String value) {
            addCriterion("us_name like", value, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameNotLike(String value) {
            addCriterion("us_name not like", value, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameIn(List<String> values) {
            addCriterion("us_name in", values, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameNotIn(List<String> values) {
            addCriterion("us_name not in", values, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameBetween(String value1, String value2) {
            addCriterion("us_name between", value1, value2, "usName");
            return (Criteria) this;
        }

        public Criteria andUsNameNotBetween(String value1, String value2) {
            addCriterion("us_name not between", value1, value2, "usName");
            return (Criteria) this;
        }

        public Criteria andUsPasswordIsNull() {
            addCriterion("us_password is null");
            return (Criteria) this;
        }

        public Criteria andUsPasswordIsNotNull() {
            addCriterion("us_password is not null");
            return (Criteria) this;
        }

        public Criteria andUsPasswordEqualTo(String value) {
            addCriterion("us_password =", value, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordNotEqualTo(String value) {
            addCriterion("us_password <>", value, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordGreaterThan(String value) {
            addCriterion("us_password >", value, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("us_password >=", value, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordLessThan(String value) {
            addCriterion("us_password <", value, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordLessThanOrEqualTo(String value) {
            addCriterion("us_password <=", value, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordLike(String value) {
            addCriterion("us_password like", value, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordNotLike(String value) {
            addCriterion("us_password not like", value, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordIn(List<String> values) {
            addCriterion("us_password in", values, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordNotIn(List<String> values) {
            addCriterion("us_password not in", values, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordBetween(String value1, String value2) {
            addCriterion("us_password between", value1, value2, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsPasswordNotBetween(String value1, String value2) {
            addCriterion("us_password not between", value1, value2, "usPassword");
            return (Criteria) this;
        }

        public Criteria andUsMobileIsNull() {
            addCriterion("us_mobile is null");
            return (Criteria) this;
        }

        public Criteria andUsMobileIsNotNull() {
            addCriterion("us_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andUsMobileEqualTo(Long value) {
            addCriterion("us_mobile =", value, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsMobileNotEqualTo(Long value) {
            addCriterion("us_mobile <>", value, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsMobileGreaterThan(Long value) {
            addCriterion("us_mobile >", value, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsMobileGreaterThanOrEqualTo(Long value) {
            addCriterion("us_mobile >=", value, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsMobileLessThan(Long value) {
            addCriterion("us_mobile <", value, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsMobileLessThanOrEqualTo(Long value) {
            addCriterion("us_mobile <=", value, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsMobileIn(List<Long> values) {
            addCriterion("us_mobile in", values, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsMobileNotIn(List<Long> values) {
            addCriterion("us_mobile not in", values, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsMobileBetween(Long value1, Long value2) {
            addCriterion("us_mobile between", value1, value2, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsMobileNotBetween(Long value1, Long value2) {
            addCriterion("us_mobile not between", value1, value2, "usMobile");
            return (Criteria) this;
        }

        public Criteria andUsEmailIsNull() {
            addCriterion("us_email is null");
            return (Criteria) this;
        }

        public Criteria andUsEmailIsNotNull() {
            addCriterion("us_email is not null");
            return (Criteria) this;
        }

        public Criteria andUsEmailEqualTo(String value) {
            addCriterion("us_email =", value, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailNotEqualTo(String value) {
            addCriterion("us_email <>", value, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailGreaterThan(String value) {
            addCriterion("us_email >", value, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailGreaterThanOrEqualTo(String value) {
            addCriterion("us_email >=", value, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailLessThan(String value) {
            addCriterion("us_email <", value, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailLessThanOrEqualTo(String value) {
            addCriterion("us_email <=", value, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailLike(String value) {
            addCriterion("us_email like", value, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailNotLike(String value) {
            addCriterion("us_email not like", value, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailIn(List<String> values) {
            addCriterion("us_email in", values, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailNotIn(List<String> values) {
            addCriterion("us_email not in", values, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailBetween(String value1, String value2) {
            addCriterion("us_email between", value1, value2, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsEmailNotBetween(String value1, String value2) {
            addCriterion("us_email not between", value1, value2, "usEmail");
            return (Criteria) this;
        }

        public Criteria andUsMessageIsNull() {
            addCriterion("us_message is null");
            return (Criteria) this;
        }

        public Criteria andUsMessageIsNotNull() {
            addCriterion("us_message is not null");
            return (Criteria) this;
        }

        public Criteria andUsMessageEqualTo(String value) {
            addCriterion("us_message =", value, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageNotEqualTo(String value) {
            addCriterion("us_message <>", value, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageGreaterThan(String value) {
            addCriterion("us_message >", value, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageGreaterThanOrEqualTo(String value) {
            addCriterion("us_message >=", value, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageLessThan(String value) {
            addCriterion("us_message <", value, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageLessThanOrEqualTo(String value) {
            addCriterion("us_message <=", value, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageLike(String value) {
            addCriterion("us_message like", value, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageNotLike(String value) {
            addCriterion("us_message not like", value, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageIn(List<String> values) {
            addCriterion("us_message in", values, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageNotIn(List<String> values) {
            addCriterion("us_message not in", values, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageBetween(String value1, String value2) {
            addCriterion("us_message between", value1, value2, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsMessageNotBetween(String value1, String value2) {
            addCriterion("us_message not between", value1, value2, "usMessage");
            return (Criteria) this;
        }

        public Criteria andUsSexIsNull() {
            addCriterion("us_sex is null");
            return (Criteria) this;
        }

        public Criteria andUsSexIsNotNull() {
            addCriterion("us_sex is not null");
            return (Criteria) this;
        }

        public Criteria andUsSexEqualTo(Integer value) {
            addCriterion("us_sex =", value, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsSexNotEqualTo(Integer value) {
            addCriterion("us_sex <>", value, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsSexGreaterThan(Integer value) {
            addCriterion("us_sex >", value, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("us_sex >=", value, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsSexLessThan(Integer value) {
            addCriterion("us_sex <", value, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsSexLessThanOrEqualTo(Integer value) {
            addCriterion("us_sex <=", value, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsSexIn(List<Integer> values) {
            addCriterion("us_sex in", values, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsSexNotIn(List<Integer> values) {
            addCriterion("us_sex not in", values, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsSexBetween(Integer value1, Integer value2) {
            addCriterion("us_sex between", value1, value2, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsSexNotBetween(Integer value1, Integer value2) {
            addCriterion("us_sex not between", value1, value2, "usSex");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayIsNull() {
            addCriterion("us_birthday is null");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayIsNotNull() {
            addCriterion("us_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("us_birthday =", value, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("us_birthday <>", value, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("us_birthday >", value, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("us_birthday >=", value, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("us_birthday <", value, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("us_birthday <=", value, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("us_birthday in", values, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("us_birthday not in", values, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("us_birthday between", value1, value2, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("us_birthday not between", value1, value2, "usBirthday");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeIsNull() {
            addCriterion("us_nowhome is null");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeIsNotNull() {
            addCriterion("us_nowhome is not null");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeEqualTo(String value) {
            addCriterion("us_nowhome =", value, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeNotEqualTo(String value) {
            addCriterion("us_nowhome <>", value, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeGreaterThan(String value) {
            addCriterion("us_nowhome >", value, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeGreaterThanOrEqualTo(String value) {
            addCriterion("us_nowhome >=", value, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeLessThan(String value) {
            addCriterion("us_nowhome <", value, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeLessThanOrEqualTo(String value) {
            addCriterion("us_nowhome <=", value, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeLike(String value) {
            addCriterion("us_nowhome like", value, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeNotLike(String value) {
            addCriterion("us_nowhome not like", value, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeIn(List<String> values) {
            addCriterion("us_nowhome in", values, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeNotIn(List<String> values) {
            addCriterion("us_nowhome not in", values, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeBetween(String value1, String value2) {
            addCriterion("us_nowhome between", value1, value2, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsNowhomeNotBetween(String value1, String value2) {
            addCriterion("us_nowhome not between", value1, value2, "usNowhome");
            return (Criteria) this;
        }

        public Criteria andUsJobIsNull() {
            addCriterion("us_job is null");
            return (Criteria) this;
        }

        public Criteria andUsJobIsNotNull() {
            addCriterion("us_job is not null");
            return (Criteria) this;
        }

        public Criteria andUsJobEqualTo(String value) {
            addCriterion("us_job =", value, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobNotEqualTo(String value) {
            addCriterion("us_job <>", value, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobGreaterThan(String value) {
            addCriterion("us_job >", value, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobGreaterThanOrEqualTo(String value) {
            addCriterion("us_job >=", value, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobLessThan(String value) {
            addCriterion("us_job <", value, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobLessThanOrEqualTo(String value) {
            addCriterion("us_job <=", value, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobLike(String value) {
            addCriterion("us_job like", value, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobNotLike(String value) {
            addCriterion("us_job not like", value, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobIn(List<String> values) {
            addCriterion("us_job in", values, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobNotIn(List<String> values) {
            addCriterion("us_job not in", values, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobBetween(String value1, String value2) {
            addCriterion("us_job between", value1, value2, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsJobNotBetween(String value1, String value2) {
            addCriterion("us_job not between", value1, value2, "usJob");
            return (Criteria) this;
        }

        public Criteria andUsHeadIsNull() {
            addCriterion("us_head is null");
            return (Criteria) this;
        }

        public Criteria andUsHeadIsNotNull() {
            addCriterion("us_head is not null");
            return (Criteria) this;
        }

        public Criteria andUsHeadEqualTo(String value) {
            addCriterion("us_head =", value, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadNotEqualTo(String value) {
            addCriterion("us_head <>", value, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadGreaterThan(String value) {
            addCriterion("us_head >", value, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadGreaterThanOrEqualTo(String value) {
            addCriterion("us_head >=", value, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadLessThan(String value) {
            addCriterion("us_head <", value, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadLessThanOrEqualTo(String value) {
            addCriterion("us_head <=", value, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadLike(String value) {
            addCriterion("us_head like", value, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadNotLike(String value) {
            addCriterion("us_head not like", value, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadIn(List<String> values) {
            addCriterion("us_head in", values, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadNotIn(List<String> values) {
            addCriterion("us_head not in", values, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadBetween(String value1, String value2) {
            addCriterion("us_head between", value1, value2, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsHeadNotBetween(String value1, String value2) {
            addCriterion("us_head not between", value1, value2, "usHead");
            return (Criteria) this;
        }

        public Criteria andUsFanscountIsNull() {
            addCriterion("us_fansCount is null");
            return (Criteria) this;
        }

        public Criteria andUsFanscountIsNotNull() {
            addCriterion("us_fansCount is not null");
            return (Criteria) this;
        }

        public Criteria andUsFanscountEqualTo(Integer value) {
            addCriterion("us_fansCount =", value, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsFanscountNotEqualTo(Integer value) {
            addCriterion("us_fansCount <>", value, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsFanscountGreaterThan(Integer value) {
            addCriterion("us_fansCount >", value, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsFanscountGreaterThanOrEqualTo(Integer value) {
            addCriterion("us_fansCount >=", value, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsFanscountLessThan(Integer value) {
            addCriterion("us_fansCount <", value, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsFanscountLessThanOrEqualTo(Integer value) {
            addCriterion("us_fansCount <=", value, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsFanscountIn(List<Integer> values) {
            addCriterion("us_fansCount in", values, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsFanscountNotIn(List<Integer> values) {
            addCriterion("us_fansCount not in", values, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsFanscountBetween(Integer value1, Integer value2) {
            addCriterion("us_fansCount between", value1, value2, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsFanscountNotBetween(Integer value1, Integer value2) {
            addCriterion("us_fansCount not between", value1, value2, "usFanscount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountIsNull() {
            addCriterion("us_bookCount is null");
            return (Criteria) this;
        }

        public Criteria andUsBookcountIsNotNull() {
            addCriterion("us_bookCount is not null");
            return (Criteria) this;
        }

        public Criteria andUsBookcountEqualTo(Integer value) {
            addCriterion("us_bookCount =", value, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountNotEqualTo(Integer value) {
            addCriterion("us_bookCount <>", value, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountGreaterThan(Integer value) {
            addCriterion("us_bookCount >", value, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("us_bookCount >=", value, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountLessThan(Integer value) {
            addCriterion("us_bookCount <", value, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountLessThanOrEqualTo(Integer value) {
            addCriterion("us_bookCount <=", value, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountIn(List<Integer> values) {
            addCriterion("us_bookCount in", values, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountNotIn(List<Integer> values) {
            addCriterion("us_bookCount not in", values, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountBetween(Integer value1, Integer value2) {
            addCriterion("us_bookCount between", value1, value2, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsBookcountNotBetween(Integer value1, Integer value2) {
            addCriterion("us_bookCount not between", value1, value2, "usBookcount");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateIsNull() {
            addCriterion("us_createdate is null");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateIsNotNull() {
            addCriterion("us_createdate is not null");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateEqualTo(Date value) {
            addCriterionForJDBCDate("us_createdate =", value, "usCreatedate");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("us_createdate <>", value, "usCreatedate");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("us_createdate >", value, "usCreatedate");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("us_createdate >=", value, "usCreatedate");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateLessThan(Date value) {
            addCriterionForJDBCDate("us_createdate <", value, "usCreatedate");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("us_createdate <=", value, "usCreatedate");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateIn(List<Date> values) {
            addCriterionForJDBCDate("us_createdate in", values, "usCreatedate");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("us_createdate not in", values, "usCreatedate");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("us_createdate between", value1, value2, "usCreatedate");
            return (Criteria) this;
        }

        public Criteria andUsCreatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("us_createdate not between", value1, value2, "usCreatedate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 14 17:34:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}