package com.qf.mapper;

import com.qf.entity.Consignee;
import com.qf.entity.ConsigneeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConsigneeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    int countByExample(ConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    int deleteByExample(ConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    int deleteByPrimaryKey(Integer conId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    int insert(Consignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    int insertSelective(Consignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    List<Consignee> selectByExample(ConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    Consignee selectByPrimaryKey(Integer conId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") Consignee record, @Param("example") ConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    int updateByExample(@Param("record") Consignee record, @Param("example") ConsigneeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    int updateByPrimaryKeySelective(Consignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Sat Apr 20 17:21:29 CST 2019
     */
    int updateByPrimaryKey(Consignee record);

    int updateConsig(Consignee consignee);

}