package com.qf.mapper;

import com.qf.entity.CookbookType;
import com.qf.entity.CookbookTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CookbookTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    int countByExample(CookbookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    int deleteByExample(CookbookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    int insert(CookbookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    int insertSelective(CookbookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    List<CookbookType> selectByExample(CookbookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    CookbookType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") CookbookType record, @Param("example") CookbookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    int updateByExample(@Param("record") CookbookType record, @Param("example") CookbookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    int updateByPrimaryKeySelective(CookbookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookbook_type
     *
     * @mbggenerated Tue Apr 09 21:38:01 CST 2019
     */
    int updateByPrimaryKey(CookbookType record);
}