package com.qf.mapper;

import com.qf.entity.TpRegion2;
import com.qf.entity.TpRegion2Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpRegion2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    int countByExample(TpRegion2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    int deleteByExample(TpRegion2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    int insert(TpRegion2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    int insertSelective(TpRegion2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    List<TpRegion2> selectByExample(TpRegion2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    TpRegion2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") TpRegion2 record, @Param("example") TpRegion2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    int updateByExample(@Param("record") TpRegion2 record, @Param("example") TpRegion2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    int updateByPrimaryKeySelective(TpRegion2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_region2
     *
     * @mbggenerated Sun Apr 14 17:34:36 CST 2019
     */
    int updateByPrimaryKey(TpRegion2 record);

    List<TpRegion2> selectparent(int parentId);
}